/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.LoginDAO;
//import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;
import static view.viewLogin.txtSenhaLogin;
import static view.viewLogin.txtUsuarioLogin;
import DAO.verificarCargoFunDAO;
import model.modelLogin;
import static view.viewPrincipal.btnClientes;
import static view.viewPrincipal.btnFuncionario;
import static view.viewPrincipal.btnProdutos;
import static view.viewPrincipal.btnRelatorios;
import static view.viewPrincipal.btnVendas;
import static view.viewPrincipal.btnFornecedor;
import static view.viewPrincipal.btnSobre;

/**
 *
 * @author Leandro Ucuamba
 */
public class viewLogin extends javax.swing.JFrame{

    /**
     * Creates new form viewLogin
     */
    public viewLogin() {
        initComponents();
        
        txtUsuarioLogin.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtSenhaLogin.setBackground(new java.awt.Color(0, 0, 0, 1));
        btnConfirmarLogin.setBackground(new java.awt.Color(0, 0, 0, 0)); // botao invisivel;
        rbVerSenha.setBackground(new java.awt.Color(0,0,0,0));
        
        // desativar o label_de_botao com efeito ao abrir tela;
        lblEfectLogin.setVisible(false);
        
        
        
    }
    
    public String retornaK()
    {
        
        String k="Comum";
        
        if( rbConfirmCargo.isSelected() )
        {
           k = "Administrador";
        }
        
        return k;
    }
    
    
    // metodo acionado ao apertar botao confirmar e KeyEvent ENTER;
    public void doBtnConfirmar(){
        
        LoginDAO dao = new LoginDAO();
        
        verificarCargoFunDAO minha = new verificarCargoFunDAO();
        
  if(rbConfirmCargo.isSelected())
  {
        
     if(minha.checkLogin(txtUsuarioLogin.getText(), txtSenhaLogin.getText(), retornaK()))
      {       
        if(dao.checkLogin(txtUsuarioLogin.getText(), txtSenhaLogin.getText()))
         {
            new viewPrincipal().setVisible(true);
            this.dispose();
         }
        else
         {
            JOptionPane.showMessageDialog(rootPane,"usuario ou senha incorreta" + JOptionPane.ERROR);
         }
      }
     else 
      {
        JOptionPane.showMessageDialog(rootPane,"Nao selecione o botao no campo usuario"
                + " voce nao é administrador" + JOptionPane.WARNING_MESSAGE);
      }
                    
  }
  
  else 
  {
      
      if(minha.checkLogin(txtUsuarioLogin.getText(), txtSenhaLogin.getText(), retornaK()))
      {       
        if(dao.checkLogin(txtUsuarioLogin.getText(), txtSenhaLogin.getText()))
         {
             
            new viewPrincipal().setVisible(true);
            this.dispose();
            
            btnFornecedor.setVisible(false);
            btnClientes.setVisible(false);
            btnFuncionario.setVisible(false);
            btnProdutos.setVisible(false);
            btnRelatorios.setVisible(false);
            btnVendas.setVisible(false);
            btnSobre.setVisible(false);
            
            
         }
        else
         {
            JOptionPane.showMessageDialog(rootPane,"usuario ou senha incorreta" + JOptionPane.ERROR);
         }
      }
      else{
          JOptionPane.showMessageDialog(rootPane,"para administrador clique no botao do campo usuario" + JOptionPane.ERROR);
      }
      
  }
    
 } //fim do btnConfirm;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEfectLogin = new javax.swing.JLabel();
        txtUsuarioLogin = new javax.swing.JTextField();
        txtSenhaLogin = new javax.swing.JPasswordField();
        rbVerSenha = new javax.swing.JRadioButton();
        rbConfirmCargo = new javax.swing.JRadioButton();
        btnConfirmarLogin = new javax.swing.JButton();
        lblPrincipalLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(655, 454));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEfectLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/loginEfect.png"))); // NOI18N
        jPanel1.add(lblEfectLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 258, 70, 50));

        txtUsuarioLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUsuarioLogin.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuarioLogin.setText("Usuario");
        txtUsuarioLogin.setBorder(null);
        txtUsuarioLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioLoginFocusLost(evt);
            }
        });
        txtUsuarioLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioLoginActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 182, 120, 22));

        txtSenhaLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSenhaLogin.setForeground(new java.awt.Color(255, 255, 255));
        txtSenhaLogin.setText("Senha");
        txtSenhaLogin.setBorder(null);
        txtSenhaLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenhaLoginFocusLost(evt);
            }
        });
        jPanel1.add(txtSenhaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 229, 120, 22));

        rbVerSenha.setText("jRadioButton1");
        rbVerSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVerSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(rbVerSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 229, 20, 20));

        rbConfirmCargo.setText("jRadioButton1");
        rbConfirmCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbConfirmCargoActionPerformed(evt);
            }
        });
        jPanel1.add(rbConfirmCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 183, 20, 20));

        btnConfirmarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfirmarLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfirmarLoginMouseExited(evt);
            }
        });
        btnConfirmarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarLoginActionPerformed(evt);
            }
        });
        btnConfirmarLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConfirmarLoginKeyPressed(evt);
            }
        });
        jPanel1.add(btnConfirmarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 272, 60, 20));

        lblPrincipalLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Login.png"))); // NOI18N
        jPanel1.add(lblPrincipalLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioLoginActionPerformed

    private void btnConfirmarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarLoginActionPerformed
            // TODO add your handling code here:
        doBtnConfirmar(); // codigo do metodo acima para ser reutilizado abaixo no KeyEvent;
        
    }//GEN-LAST:event_btnConfirmarLoginActionPerformed

    private void txtUsuarioLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioLoginFocusGained
        // TODO add your handling code here:
        if(txtUsuarioLogin.getText().trim().equals("Usuario"))
        {
            txtUsuarioLogin.setText("");
        }
    }//GEN-LAST:event_txtUsuarioLoginFocusGained

    private void txtUsuarioLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioLoginFocusLost
        // TODO add your handling code here:
        if(txtUsuarioLogin.getText().trim().equals(""))
        {
            txtUsuarioLogin.setText("Usuario");
        }
    }//GEN-LAST:event_txtUsuarioLoginFocusLost

    private void txtSenhaLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaLoginFocusGained
        // TODO add your handling code here:
        if(txtSenhaLogin.getText().trim().equals("Senha"))
        {
            txtSenhaLogin.setText("");
        }
    }//GEN-LAST:event_txtSenhaLoginFocusGained

    private void txtSenhaLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaLoginFocusLost
        // TODO add your handling code here:
        if(txtSenhaLogin.getText().trim().equals(""))
        {
            txtSenhaLogin.setText("Senha");
        }
    }//GEN-LAST:event_txtSenhaLoginFocusLost

    private void rbVerSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVerSenhaActionPerformed
        // TODO add your handling code here:
        if(rbVerSenha.isSelected())
        {
            txtSenhaLogin.setEchoChar((char)0);
        }
        else
        {
            txtSenhaLogin.setEchoChar('*');
        }
        
    }//GEN-LAST:event_rbVerSenhaActionPerformed

    private void btnConfirmarLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConfirmarLoginKeyPressed
            // TODO add your handling code her
    }//GEN-LAST:event_btnConfirmarLoginKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here
    }//GEN-LAST:event_formKeyPressed

    private void btnConfirmarLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarLoginMouseEntered
        // TODO add your handling code here:
        lblEfectLogin.setVisible(true);
    }//GEN-LAST:event_btnConfirmarLoginMouseEntered

    private void btnConfirmarLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarLoginMouseExited
        // TODO add your handling code here:
        lblEfectLogin.setVisible(false);
    }//GEN-LAST:event_btnConfirmarLoginMouseExited

    private void rbConfirmCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbConfirmCargoActionPerformed
        // TODO add your handling code here:     
            
    }//GEN-LAST:event_rbConfirmCargoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewLogin().setVisible(true);
            }
        });
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEfectLogin;
    private javax.swing.JLabel lblPrincipalLogin;
    private javax.swing.JRadioButton rbConfirmCargo;
    private javax.swing.JRadioButton rbVerSenha;
    public static javax.swing.JPasswordField txtSenhaLogin;
    public static javax.swing.JTextField txtUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
