/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.FuncionarioDAO;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.JOptionPane;
import model.modelFuncionario;
import static view.viewFuncionario.rbAdministrador;
import static view.viewFuncionario.rbComum;
import static view.viewFuncionario.rbFemenino;
import static view.viewFuncionario.rbMasculino;
import static view.viewFuncionario.txtMoradaFun;
import static view.viewFuncionario.txtNifLoja;
import static view.viewFuncionario.txtNomeFun;
import static view.viewFuncionario.txtNumeroBI;
import static view.viewFuncionario.txtSenhaLog;
import static view.viewFuncionario.txtTelefoneFun;
import static view.viewFuncionario.txtUsuarioLog;
import view.validarCampos;

/**
 *
 * @author Leandro Ucuamba
 */
public class viewFuncionario1 extends javax.swing.JFrame {

    /**
     * Creates new form viewFuncionario1
     */
    public viewFuncionario1() {
        initComponents();
        
        btnHome2.setBackground(new java.awt.Color(0, 0, 0, 0));
        
        readJTable1();
    }
    
    
    public void readJTable1() {
        DefaultTableModel modelo = (DefaultTableModel) jtFuncionario.getModel();
        modelo.setNumRows(0); // para quando apresentar na JTable apois um cadastro não duplicar valores;

        FuncionarioDAO cliDao = new FuncionarioDAO();

        // este é o ForEach;
        for (modelFuncionario pesqFun : cliDao.read1()) {
            modelo.addRow(new Object[]{
                pesqFun.getId_funcionario(),
                pesqFun.getNomeFun(),
                pesqFun.getTelefoneFun(),
                pesqFun.getCargoFun(),
                pesqFun.getDataNascimento(),
                pesqFun.getMorada(),
                pesqFun.getSexo(),
                pesqFun.getnBI(),
                pesqFun.getUsuarioLogin(),
                pesqFun.getSenhaLogin()
            });
        }
    }
    
    public void readJTableForName1(String meuK) {
        DefaultTableModel modelo = (DefaultTableModel) jtFuncionario.getModel();
        modelo.setNumRows(0); // para quando apresentar na JTable apois um cadastro não duplicar valores;

        FuncionarioDAO cliDao = new FuncionarioDAO();

        // este é o ForEach;
        for (modelFuncionario pesqFun : cliDao.readForNome1(meuK)) {
            modelo.addRow(new Object[]{
                pesqFun.getId_funcionario(),
                pesqFun.getNomeFun(),
                pesqFun.getTelefoneFun(),
                pesqFun.getCargoFun(),
                pesqFun.getDataNascimento(),
                pesqFun.getMorada(),
                pesqFun.getSexo(),
                pesqFun.getnBI(),
                pesqFun.getUsuarioLogin(),
                pesqFun.getSenhaLogin()
            });
        }
    }
    
    validarCampos k = new validarCampos();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtFuncionario = new javax.swing.JTable();
        txtBarraPesq = new javax.swing.JTextField();
        btnPesq1 = new javax.swing.JButton();
        btnPesq2 = new javax.swing.JButton();
        btnRemoverFun = new javax.swing.JButton();
        btnHome2 = new javax.swing.JButton();
        imgPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Telefone", "Cargo", "Data de Nascimento", "Morada", "Sexo", "Numero do BI", "Usuario", "Senha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtFuncionarioKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtFuncionario);
        if (jtFuncionario.getColumnModel().getColumnCount() > 0) {
            jtFuncionario.getColumnModel().getColumn(0).setMinWidth(68);
            jtFuncionario.getColumnModel().getColumn(0).setMaxWidth(10);
            jtFuncionario.getColumnModel().getColumn(4).setMinWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 960, 200));

        txtBarraPesq.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBarraPesq.setText("Pesquisar por nome");
        txtBarraPesq.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBarraPesqFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBarraPesqFocusLost(evt);
            }
        });
        txtBarraPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBarraPesqKeyTyped(evt);
            }
        });
        jPanel1.add(txtBarraPesq, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 480, 30));

        btnPesq1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lupa.png"))); // NOI18N
        btnPesq1.setText("Pesquisar");
        btnPesq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesq1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, 110, -1));

        btnPesq2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lupa.png"))); // NOI18N
        btnPesq2.setText("Pesquisar todos");
        btnPesq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesq2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesq2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, 160, -1));

        btnRemoverFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/eliCadastro.png"))); // NOI18N
        btnRemoverFun.setText("Remover");
        btnRemoverFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverFunActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemoverFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 110, -1));

        btnHome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(963, 70, 50, 30));

        imgPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sub.png"))); // NOI18N
        jPanel1.add(imgPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 665));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverFunActionPerformed
        // TODO add your handling code here:
        
        // getSeletedRow() -> linha selecionada;
        if (jtFuncionario.getSelectedRow() != -1) {
             
            modelFuncionario p = new modelFuncionario();
            FuncionarioDAO dao = new FuncionarioDAO();
            
            p.setId_funcionario((int)jtFuncionario.getValueAt(jtFuncionario.getSelectedRow(), 0));
            
            dao.delete(p);

            // codigo para limpar campo apois o registro;
        rbAdministrador.setSelected(false);
        rbComum.setSelected(false);
        rbFemenino.setSelected(false);
        rbMasculino.setSelected(false);
        txtMoradaFun.setText("");
        txtNifLoja.setText("");
        txtNumeroBI.setText("");
        txtNomeFun.setText("");
        txtTelefoneFun.setText("");
        txtUsuarioLog.setText("");
        txtSenhaLog.setText("");
            //fecho da limpa nos campos
            readJTable1();
        }
        else{
            JOptionPane.showMessageDialog(null, "selecciona um cliente para excluir");
        }
        
    }//GEN-LAST:event_btnRemoverFunActionPerformed

    private void txtBarraPesqFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBarraPesqFocusGained
        // TODO add your handling code here:
        if(txtBarraPesq.getText().trim().equals("Pesquisar por nome"))
        {
            txtBarraPesq.setText("");
        }
    }//GEN-LAST:event_txtBarraPesqFocusGained

    private void txtBarraPesqFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBarraPesqFocusLost
        // TODO add your handling code here:
        if(txtBarraPesq.getText().trim().equals(""))
        {
            txtBarraPesq.setText("Pesquisar por nome");
        }
    }//GEN-LAST:event_txtBarraPesqFocusLost

    private void jtFuncionarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtFuncionarioKeyPressed
        // TODO add your handling code here;
         
    }//GEN-LAST:event_jtFuncionarioKeyPressed

    private void btnHome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        new viewPrincipal().setVisible(true);
    }//GEN-LAST:event_btnHome2ActionPerformed

    private void btnPesq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesq2ActionPerformed
        // TODO add your handling code here:
        readJTable1();

    }//GEN-LAST:event_btnPesq2ActionPerformed

    private void btnPesq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesq1ActionPerformed
        // TODO add your handling code here:
        readJTableForName1(txtBarraPesq.getText());
    }//GEN-LAST:event_btnPesq1ActionPerformed

    private void txtBarraPesqKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBarraPesqKeyTyped
        // TODO add your handling code here:
        k.validarNumeros(evt);
    }//GEN-LAST:event_txtBarraPesqKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewFuncionario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewFuncionario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewFuncionario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewFuncionario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewFuncionario1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome2;
    private javax.swing.JButton btnPesq1;
    private javax.swing.JButton btnPesq2;
    private javax.swing.JButton btnRemoverFun;
    private javax.swing.JLabel imgPrincipal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtFuncionario;
    private javax.swing.JTextField txtBarraPesq;
    // End of variables declaration//GEN-END:variables
}
