/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

//import com.sun.glass.ui.Cursor;
import java.awt.Color;
import static view.viewLogin.txtUsuarioLogin; // importacao da caixa de texto usuario do login;

/**
 *
 * @author Leandro Ucuamba
 */
public class viewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form viewPrincipal
     */
    public viewPrincipal() {
        initComponents();
        
        //captura texto da caixa de login usuario;
        lblNomeUser.setText(txtUsuarioLogin.getText());
        //codigos para deixar os botoes invisiveis
        btnFuncionario.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnVendas.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnClientes.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnProdutos.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnCaixa.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnRelatorios.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnCaixa.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnSobre.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnLogout.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnFornecedor.setBackground(new java.awt.Color(0, 0, 0, 0));
        
        // tornando as label de imagem ampliadas nula (invisiveis);
        lblEfect1.setVisible(false);
        lblEfect2.setVisible(false);
        lblEfect3.setVisible(false);
        lblEfect4.setVisible(false);
        lblEfect5.setVisible(false);
        lblEfect6.setVisible(false);
        
        lblFornecedor.setVisible(false);
        lblSobre.setVisible(false);
        lblLogout.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVendas = new javax.swing.JButton();
        btnCaixa = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();
        lblNomeStatico = new javax.swing.JLabel();
        lblNomeUser = new javax.swing.JLabel();
        btnFornecedor = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnSobre = new javax.swing.JButton();
        btnFuncionario = new javax.swing.JButton();
        lblEfect6 = new javax.swing.JLabel();
        lblEfect5 = new javax.swing.JLabel();
        lblEfect4 = new javax.swing.JLabel();
        lblEfect1 = new javax.swing.JLabel();
        lblEfect3 = new javax.swing.JLabel();
        lblEfect2 = new javax.swing.JLabel();
        lblFornecedor = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        lblSobre = new javax.swing.JLabel();
        labelImagemPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVendasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVendasMouseExited(evt);
            }
        });
        jPanel1.add(btnVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 130, 100));

        btnCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCaixaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCaixaMouseExited(evt);
            }
        });
        btnCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 130, 100));

        btnProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProdutosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProdutosMouseExited(evt);
            }
        });
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });
        jPanel1.add(btnProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 140, 100));

        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClientesMouseExited(evt);
            }
        });
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 130, 110));

        btnRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRelatoriosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRelatoriosMouseExited(evt);
            }
        });
        btnRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatoriosActionPerformed(evt);
            }
        });
        jPanel1.add(btnRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 140, 110));

        lblNomeStatico.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNomeStatico.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeStatico.setText("Bem Vindo :");
        jPanel1.add(lblNomeStatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 90, 20));

        lblNomeUser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNomeUser.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblNomeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 130, 20));

        btnFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFornecedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFornecedorMouseExited(evt);
            }
        });
        btnFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(btnFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 70, 30));

        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 80, 50, 30));

        btnSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSobreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSobreMouseExited(evt);
            }
        });
        btnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobreActionPerformed(evt);
            }
        });
        jPanel1.add(btnSobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 80, 50, 30));

        btnFuncionario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFuncionarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFuncionarioMouseExited(evt);
            }
        });
        btnFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 130, 100));

        lblEfect6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/relatorioEfect.png"))); // NOI18N
        jPanel1.add(lblEfect6, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 424, 160, 140));

        lblEfect5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clienteEfect.png"))); // NOI18N
        jPanel1.add(lblEfect5, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 434, 160, 120));

        lblEfect4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/produtosEfect.png"))); // NOI18N
        jPanel1.add(lblEfect4, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 310, 160, 120));

        lblEfect1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/funcionarioEfect.png"))); // NOI18N
        jPanel1.add(lblEfect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 196, 160, 110));

        lblEfect3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/caixaEfect.png"))); // NOI18N
        jPanel1.add(lblEfect3, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 310, 160, 120));

        lblEfect2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/vendasEfect.png"))); // NOI18N
        jPanel1.add(lblEfect2, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 191, 160, 120));

        lblFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/fornecedor.png"))); // NOI18N
        jPanel1.add(lblFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(805, 76, 100, 40));

        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jPanel1.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(894, 75, 70, 40));

        lblSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sobre.png"))); // NOI18N
        jPanel1.add(lblSobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(949, 76, 50, 40));

        labelImagemPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal.png"))); // NOI18N
        labelImagemPrincipal.setToolTipText("");
        jPanel1.add(labelImagemPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        
        new viewPrincipal().setVisible(false);
        this.dispose();
        viewCliente novo1 = new viewCliente();
        novo1.setVisible(true);
        
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnFuncionarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionarioMouseEntered
        // TODO add your handling code here
        lblEfect1.setVisible(true);
    }//GEN-LAST:event_btnFuncionarioMouseEntered

    private void btnFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionarioActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        new viewFuncionario().setVisible(true);
    }//GEN-LAST:event_btnFuncionarioActionPerformed

    private void btnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelatoriosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        
        new viewPrincipal().setVisible(false);
        this.dispose();
        new viewLogin().setVisible(true);
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnFuncionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionarioMouseExited
        // TODO add your handling code here:
        lblEfect1.setVisible(false);
    }//GEN-LAST:event_btnFuncionarioMouseExited

    private void btnVendasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendasMouseEntered
        // TODO add your handling code here:
        lblEfect2.setVisible(true);
    }//GEN-LAST:event_btnVendasMouseEntered

    private void btnVendasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendasMouseExited
        // TODO add your handling code here:
        lblEfect2.setVisible(false);
    }//GEN-LAST:event_btnVendasMouseExited

    private void btnCaixaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCaixaMouseEntered
        // TODO add your handling code here:
        lblEfect3.setVisible(true);
    }//GEN-LAST:event_btnCaixaMouseEntered

    private void btnCaixaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCaixaMouseExited
        // TODO add your handling code here:
        lblEfect3.setVisible(false);
    }//GEN-LAST:event_btnCaixaMouseExited

    private void btnProdutosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutosMouseEntered
        // TODO add your handling code here:
        lblEfect4.setVisible(true);
    }//GEN-LAST:event_btnProdutosMouseEntered

    private void btnProdutosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutosMouseExited
        // TODO add your handling code here:
        lblEfect4.setVisible(false);
    }//GEN-LAST:event_btnProdutosMouseExited

    private void btnClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseEntered
        // TODO add your handling code here:
        lblEfect5.setVisible(true);
    }//GEN-LAST:event_btnClientesMouseEntered

    private void btnClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseExited
        // TODO add your handling code here:
        lblEfect5.setVisible(false);
    }//GEN-LAST:event_btnClientesMouseExited

    private void btnRelatoriosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatoriosMouseEntered
        // TODO add your handling code here:
        lblEfect6.setVisible(true);
    }//GEN-LAST:event_btnRelatoriosMouseEntered

    private void btnRelatoriosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatoriosMouseExited
        // TODO add your handling code here:
        lblEfect6.setVisible(false);
    }//GEN-LAST:event_btnRelatoriosMouseExited

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        new viewProduto().setVisible(true);
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        new viewFornecedor().setVisible(true);
    }//GEN-LAST:event_btnFornecedorActionPerformed

    private void btnFornecedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFornecedorMouseEntered
        // TODO add your handling code here:
        lblFornecedor.setVisible(true);
    }//GEN-LAST:event_btnFornecedorMouseEntered

    private void btnFornecedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFornecedorMouseExited
        // TODO add your handling code here:
        lblFornecedor.setVisible(false);
    }//GEN-LAST:event_btnFornecedorMouseExited

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        lblLogout.setVisible(true);
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        lblLogout.setVisible(false);
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnSobreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSobreMouseEntered
        // TODO add your handling code here:
        lblSobre.setVisible(true);
    }//GEN-LAST:event_btnSobreMouseEntered

    private void btnSobreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSobreMouseExited
        // TODO add your handling code here:
        lblSobre.setVisible(false);
    }//GEN-LAST:event_btnSobreMouseExited

    private void btnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        this.dispose();
        new viewEscolher().setVisible(true);
    }//GEN-LAST:event_btnSobreActionPerformed

    private void btnCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        new viewCaixa().setVisible(true);
    }//GEN-LAST:event_btnCaixaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewPrincipal().setVisible(true);
            }
        });       
             
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaixa;
    public static javax.swing.JButton btnClientes;
    public static javax.swing.JButton btnFornecedor;
    public static javax.swing.JButton btnFuncionario;
    private javax.swing.JButton btnLogout;
    public static javax.swing.JButton btnProdutos;
    public static javax.swing.JButton btnRelatorios;
    public static javax.swing.JButton btnSobre;
    public static javax.swing.JButton btnVendas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelImagemPrincipal;
    private javax.swing.JLabel lblEfect1;
    private javax.swing.JLabel lblEfect2;
    private javax.swing.JLabel lblEfect3;
    private javax.swing.JLabel lblEfect4;
    private javax.swing.JLabel lblEfect5;
    private javax.swing.JLabel lblEfect6;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblNomeStatico;
    private javax.swing.JLabel lblNomeUser;
    private javax.swing.JLabel lblSobre;
    // End of variables declaration//GEN-END:variables


}
