/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Leandro Ucuamba
 */
public class viewSplash extends javax.swing.JFrame {

    /**
     * Creates new form viewSplash
     */
    public viewSplash() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        labelProgress = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setFocusableWindowState(false);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar1.setBackground(new java.awt.Color(153, 153, 153));
        jProgressBar1.setForeground(new java.awt.Color(0, 204, 51));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 146, 320, 17));

        labelProgress.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        labelProgress.setForeground(new java.awt.Color(51, 51, 51));
        labelProgress.setText("0%");
        getContentPane().add(labelProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 30, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/splach.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
// Este é o codigo do progress bar;
        viewSplash pl = new viewSplash();//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                pl.setVisible(true);
            }
        });
        
        
        viewLogin k = new viewLogin();
        try{
             for(int i=0; i<=100; i++)
               {
                 Thread.sleep(20);
                 pl.jProgressBar1.setValue(i);
                 pl.labelProgress.setText(Integer.toString(i)+"%");
                 
                
               }
        
           } catch(Exception e)
           {}
        
            new viewSplash().setVisible(false);
            k.setVisible(true);
            pl.dispose();
    // aqui fecha o trecho de codigo do progressBar;    
          
    } // fecho do metodo main();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JProgressBar jProgressBar1;
    public javax.swing.JLabel labelProgress;
    // End of variables declaration//GEN-END:variables
}
