/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.FuncionarioDAO;
import model.modelFuncionario;
import javax.swing.JOptionPane;
import view.validarCampos;

/**
 *
 * @author Leandro Ucuamba
 */
public class viewFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form viewFuncionario
     */
    public viewFuncionario() {
        initComponents();
        
        btnHome1.setBackground(new java.awt.Color(0, 0, 0, 0));
        
        txtEditData.setBackground(new java.awt.Color(0, 0, 0, 0));
        
    }
    
    validarCampos k = new validarCampos();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelCredenciais = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtUsuarioLog = new javax.swing.JTextField();
        txtSenhaLog = new javax.swing.JTextField();
        txtIdFun = new javax.swing.JTextField();
        txtNomeFun = new javax.swing.JTextField();
        txtTelefoneFun = new javax.swing.JTextField();
        txtMoradaFun = new javax.swing.JTextField();
        txtNumeroBI = new javax.swing.JTextField();
        txtNifLoja = new javax.swing.JTextField();
        rbMasculino = new javax.swing.JRadioButton();
        rbFemenino = new javax.swing.JRadioButton();
        rbAdministrador = new javax.swing.JRadioButton();
        rbComum = new javax.swing.JRadioButton();
        btnCancelarFun = new javax.swing.JButton();
        btnGuardarFun = new javax.swing.JButton();
        btnHome1 = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        txtPesqAlter = new javax.swing.JTextField();
        btnPesqAlterFun = new javax.swing.JButton();
        txtEditData = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblPrincipal1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefone:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cargo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data de Nascimento");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Morada:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sexo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Número do BI:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nif da Loja:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        panelCredenciais.setBackground(new java.awt.Color(102, 102, 102));
        panelCredenciais.setForeground(new java.awt.Color(102, 102, 102));

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel12.setText("Credenciais");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Usuario:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Senha:");

        txtUsuarioLog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUsuarioLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioLogActionPerformed(evt);
            }
        });

        txtSenhaLog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout panelCredenciaisLayout = new javax.swing.GroupLayout(panelCredenciais);
        panelCredenciais.setLayout(panelCredenciaisLayout);
        panelCredenciaisLayout.setHorizontalGroup(
            panelCredenciaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCredenciaisLayout.createSequentialGroup()
                .addGroup(panelCredenciaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCredenciaisLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(panelCredenciaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelCredenciaisLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtSenhaLog))
                            .addGroup(panelCredenciaisLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUsuarioLog, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelCredenciaisLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel12)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        panelCredenciaisLayout.setVerticalGroup(
            panelCredenciaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCredenciaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCredenciaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCredenciaisLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel9))
                    .addComponent(txtUsuarioLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(panelCredenciaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(txtSenhaLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jPanel1.add(panelCredenciais, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 320, 220));

        txtIdFun.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtIdFun.setEnabled(false);
        jPanel1.add(txtIdFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 100, -1));

        txtNomeFun.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNomeFun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeFunKeyTyped(evt);
            }
        });
        jPanel1.add(txtNomeFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 194, 240, 26));

        txtTelefoneFun.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTelefoneFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneFunActionPerformed(evt);
            }
        });
        txtTelefoneFun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefoneFunKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefoneFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 241, 220, 30));

        txtMoradaFun.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMoradaFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMoradaFunActionPerformed(evt);
            }
        });
        jPanel1.add(txtMoradaFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 293, 230, 30));

        txtNumeroBI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtNumeroBI, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 343, 180, 30));

        txtNifLoja.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNifLoja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNifLojaKeyTyped(evt);
            }
        });
        jPanel1.add(txtNifLoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 393, 210, 30));

        rbMasculino.setBackground(new java.awt.Color(51, 51, 51));
        rbMasculino.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbMasculino.setForeground(new java.awt.Color(255, 255, 255));
        rbMasculino.setText("Masculino");
        rbMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMasculinoActionPerformed(evt);
            }
        });
        jPanel1.add(rbMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, 20));

        rbFemenino.setBackground(new java.awt.Color(51, 51, 51));
        rbFemenino.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbFemenino.setForeground(new java.awt.Color(255, 255, 255));
        rbFemenino.setText("Femenino");
        rbFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemeninoActionPerformed(evt);
            }
        });
        jPanel1.add(rbFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, 20));

        rbAdministrador.setBackground(new java.awt.Color(51, 51, 51));
        rbAdministrador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        rbAdministrador.setText("Administrador");
        rbAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAdministradorActionPerformed(evt);
            }
        });
        jPanel1.add(rbAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 120, 20));

        rbComum.setBackground(new java.awt.Color(51, 51, 51));
        rbComum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbComum.setForeground(new java.awt.Color(255, 255, 255));
        rbComum.setText("Comum");
        rbComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbComumActionPerformed(evt);
            }
        });
        jPanel1.add(rbComum, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, -1, 20));

        btnCancelarFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cancel.png"))); // NOI18N
        btnCancelarFun.setText("Cancelar");
        btnCancelarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarFunActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelarFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, -1, 24));

        btnGuardarFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/guardar.png"))); // NOI18N
        btnGuardarFun.setText("Guardar");
        btnGuardarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarFunActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 100, 24));

        btnHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 50, 50, 30));

        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lupa.png"))); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        jPanel1.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 100, -1));

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/actualizar.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 110, -1));

        txtPesqAlter.setText("Insira o id do funcionario que pretende actualizar");
        txtPesqAlter.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesqAlterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesqAlterFocusLost(evt);
            }
        });
        txtPesqAlter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesqAlterKeyTyped(evt);
            }
        });
        jPanel1.add(txtPesqAlter, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 300, 30));

        btnPesqAlterFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lupa.png"))); // NOI18N
        btnPesqAlterFun.setText("Pesquisar");
        btnPesqAlterFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqAlterFunActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesqAlterFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 110, 30));

        txtEditData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEditData.setForeground(new java.awt.Color(255, 255, 255));
        txtEditData.setText("ANO-MES-DIA");
        txtEditData.setBorder(null);
        txtEditData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEditDataFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEditDataFocusLost(evt);
            }
        });
        txtEditData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEditDataKeyTyped(evt);
            }
        });
        jPanel1.add(txtEditData, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 190, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 190, 10));

        lblPrincipal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sub.png"))); // NOI18N
        jPanel1.add(lblPrincipal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMoradaFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMoradaFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMoradaFunActionPerformed

    private void txtUsuarioLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioLogActionPerformed

    private void btnGuardarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarFunActionPerformed
        // TODO add your handling code here:
        
        String Ccargo;
        String Ssexo;
        
        if(rbAdministrador.isSelected())
        {
            Ccargo = "Administrador";
        }
        else{
            Ccargo = "Comum";
        }
        
        
        if(rbMasculino.isSelected())
        {
            Ssexo = "Masculino";
        }
        else{
            Ssexo = "Femenino";
        }
        
        modelFuncionario p = new modelFuncionario();
        FuncionarioDAO dao = new FuncionarioDAO();
        
        p.setNomeFun(txtNomeFun.getText());
        p.setTelefoneFun(Integer.parseInt(txtTelefoneFun.getText()));
        p.setMorada(txtMoradaFun.getText());
        p.setCargoFun(Ccargo);
        p.setDataNascimento(txtEditData.getText());
        p.setSexo(Ssexo);
        p.setnBI(txtNumeroBI.getText());
        p.setUsuarioLogin(txtUsuarioLog.getText());
        p.setSenhaLogin(txtSenhaLog.getText());
        p.setMorada(txtMoradaFun.getText());
        p.setNifLoja(txtNifLoja.getText());
        dao.create(p);
        
        this.setVisible(false);
        this.dispose();
        new viewFuncionario1().setVisible(true);
        
        // Limpar campos apois o cadastro de funcionario;
        rbAdministrador.setSelected(false);
        rbComum.setSelected(false);
        rbFemenino.setSelected(false);
        rbMasculino.setSelected(false);
        txtEditData.setText("");
        txtMoradaFun.setText("");
        txtNifLoja.setText("");
        txtNumeroBI.setText("");
        txtNomeFun.setText("");
        txtTelefoneFun.setText("");
        txtUsuarioLog.setText("");
        txtSenhaLog.setText("");
        
        new viewFuncionario1().readJTable1();
    }//GEN-LAST:event_btnGuardarFunActionPerformed

    private void rbMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMasculinoActionPerformed
        // TODO add your handling code here:
        
        if(rbMasculino.isSelected())
        {
            rbFemenino.setSelected(false);
        }
    }//GEN-LAST:event_rbMasculinoActionPerformed

    private void rbFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemeninoActionPerformed
        // TODO add your handling code here:
        if(rbFemenino.isSelected())
        {
            rbMasculino.setSelected(false);
        }
    }//GEN-LAST:event_rbFemeninoActionPerformed

    private void rbAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAdministradorActionPerformed
        // TODO add your handling code here:
        if(rbAdministrador.isSelected())
        {
            rbComum.setSelected(false);
        }
    }//GEN-LAST:event_rbAdministradorActionPerformed

    private void rbComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbComumActionPerformed
        // TODO add your handling code here:
        if(rbComum.isSelected())
        {
            rbAdministrador.setSelected(false);
        }
    }//GEN-LAST:event_rbComumActionPerformed

    private void txtTelefoneFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneFunActionPerformed

    private void btnCancelarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarFunActionPerformed
        // TODO add your handling code here:
        
        rbAdministrador.setSelected(false);
        rbComum.setSelected(false);
        rbFemenino.setSelected(false);
        rbMasculino.setSelected(false);
        txtEditData.setText("");
        txtMoradaFun.setText("");
        txtNifLoja.setText("");
        txtNumeroBI.setText("");
        txtNomeFun.setText("");
        txtTelefoneFun.setText("");
        txtUsuarioLog.setText("");
        txtSenhaLog.setText("");
        
    }//GEN-LAST:event_btnCancelarFunActionPerformed

    private void btnHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        new viewPrincipal().setVisible(true);
    }//GEN-LAST:event_btnHome1ActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        new viewFuncionario1().setVisible(true);
        
        new viewFuncionario1().readJTable1();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        
        String Ccargo;
        String Ssexo;
        
        if(rbAdministrador.isSelected())
        {
            Ccargo = "Administrador";
        }
        else{
            Ccargo = "Comum";
        }
        
        
        if(rbMasculino.isSelected())
        {
            Ssexo = "Masculino";
        }
        else{
            Ssexo = "Femenino";
        }
        
        modelFuncionario p = new modelFuncionario();
        FuncionarioDAO dao = new FuncionarioDAO();
        
        p.setId_funcionario(Integer.parseInt(txtIdFun.getText()));
        p.setNomeFun(txtNomeFun.getText());
        p.setTelefoneFun(Integer.parseInt(txtTelefoneFun.getText()));
        p.setMorada(txtMoradaFun.getText());
        p.setCargoFun(Ccargo);
        p.setDataNascimento(txtEditData.getText());
        p.setSexo(Ssexo);
        p.setnBI(txtNumeroBI.getText());
        p.setUsuarioLogin(txtUsuarioLog.getText());
        p.setSenhaLogin(txtSenhaLog.getText());
        p.setMorada(txtMoradaFun.getText());
        p.setNifLoja(txtNifLoja.getText());
        dao.update(p);
        
        // Limpar campos apois o cadastro de funcionario;
        txtIdFun.setText("");
        rbAdministrador.setSelected(false);
        rbComum.setSelected(false);
        rbFemenino.setSelected(false);
        rbMasculino.setSelected(false);
        txtEditData.setText("");
        txtMoradaFun.setText("");
        txtNifLoja.setText("");
        txtNumeroBI.setText("");
        txtNomeFun.setText("");
        txtTelefoneFun.setText("");
        txtUsuarioLog.setText("");
        txtSenhaLog.setText("");
        
        new viewFuncionario1().readJTable1();
        
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtPesqAlterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesqAlterFocusGained
        // TODO add your handling code here:
        
        if(txtPesqAlter.getText().trim().equals("Insira o id do funcionario que pretende actualizar"))
        {
            txtPesqAlter.setText("");
        }
    }//GEN-LAST:event_txtPesqAlterFocusGained

    private void txtPesqAlterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesqAlterFocusLost
        // TODO add your handling code here:
        
        if(txtPesqAlter.getText().trim().equals(""))
        {
            txtPesqAlter.setText("Insira o id do funcionario que pretende actualizar");
        }
    }//GEN-LAST:event_txtPesqAlterFocusLost

    private void btnPesqAlterFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqAlterFunActionPerformed
        // TODO add your handling code here:
       
        
        int pesquisar = Integer.parseInt(txtPesqAlter.getText());
        FuncionarioDAO fDAO = new FuncionarioDAO();
        // Aqui criei uma variavel do tipo modelFuncionario;
        modelFuncionario k = fDAO.getFuncionario(pesquisar);
                
        if(k == null)
        {
            JOptionPane.showMessageDialog(this, "Funcionario não encontrado");
            
        }
        else
        {
            // Preencher o campos do form com os dados do retorno;
            txtIdFun.setText(String.valueOf(k.getId_funcionario()));
            txtNomeFun.setText(k.getNomeFun());
            txtTelefoneFun.setText(String.valueOf(k.getTelefoneFun()));
            txtMoradaFun.setText(k.getMorada());
            txtNumeroBI.setText(k.getnBI());
            txtEditData.setText(k.getDataNascimento());
            txtUsuarioLog.setText(k.getUsuarioLogin());
            txtSenhaLog.setText(k.getSenhaLogin());
            if(k.getCargoFun().trim().equals("Administrador"))
             {
                rbAdministrador.setSelected(true);
             }
             else{
                rbAdministrador.setSelected(false);
                rbComum.setSelected(true);
             }
        
            if(k.getSexo().trim().equals("Masculino"))
             {
               rbMasculino.setSelected(true);
             }
            else{
               rbMasculino.setSelected(false);
               rbFemenino.setSelected(true);
             }
            
        }
        
    }//GEN-LAST:event_btnPesqAlterFunActionPerformed

    private void txtEditDataFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEditDataFocusGained
        // TODO add your handling code here:
        if(txtEditData.getText().trim().equals("ANO-MES-DIA"))
        {
            txtEditData.setText("");
        }
    }//GEN-LAST:event_txtEditDataFocusGained

    private void txtEditDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEditDataFocusLost
        // TODO add your handling code here:
        if(txtEditData.getText().trim().equals(""))
        {
            txtEditData.setText("ANO-MES-DIA");
        }
    }//GEN-LAST:event_txtEditDataFocusLost

    private void txtNomeFunKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFunKeyTyped
        // TODO add your handling code here:
        k.validarNumeros(evt);
    }//GEN-LAST:event_txtNomeFunKeyTyped

    private void txtTelefoneFunKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneFunKeyTyped
        // TODO add your handling code here:
        k.validarText(evt);
    }//GEN-LAST:event_txtTelefoneFunKeyTyped

    private void txtNifLojaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNifLojaKeyTyped
        // TODO add your handling code here:
        k.validarText(evt);
    }//GEN-LAST:event_txtNifLojaKeyTyped

    private void txtPesqAlterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqAlterKeyTyped
        // TODO add your handling code here:
        k.validarText(evt);
    }//GEN-LAST:event_txtPesqAlterKeyTyped

    private void txtEditDataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditDataKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtEditDataKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelarFun;
    private javax.swing.JButton btnGuardarFun;
    private javax.swing.JButton btnHome1;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnPesqAlterFun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblPrincipal1;
    private javax.swing.JPanel panelCredenciais;
    public static javax.swing.JRadioButton rbAdministrador;
    public static javax.swing.JRadioButton rbComum;
    public static javax.swing.JRadioButton rbFemenino;
    public static javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTextField txtEditData;
    private javax.swing.JTextField txtIdFun;
    public static javax.swing.JTextField txtMoradaFun;
    public static javax.swing.JTextField txtNifLoja;
    public static javax.swing.JTextField txtNomeFun;
    public static javax.swing.JTextField txtNumeroBI;
    private javax.swing.JTextField txtPesqAlter;
    public static javax.swing.JTextField txtSenhaLog;
    public static javax.swing.JTextField txtTelefoneFun;
    public static javax.swing.JTextField txtUsuarioLog;
    // End of variables declaration//GEN-END:variables
}
